//EJEMPLO DE TIPOS
//export const LISTAR_POKEMONS = 'LISTAR_POKEMONS';

//TIPOS DEL HOME
export const SET_HOME_LISTAR_PRODUCTOS = 'SET_HOME_LISTAR_PRODUCTOS';
export const SET_HOME_ERROR_POKEMONS = 'SET_HOME_ERROR_POKEMONS';
export const SET_HOME_LOADING_POKEMONS = 'SET_HOME_LOADING_POKEMONS';